spring.application.name=CodeBrawl

#jwt.secretKey=thisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkey


spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/codebrawl
spring.datasource.username=postgres
spring.datasource.password=@Bimshuthedeveloper_0562

#server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.security.user.name=bimarsha
spring.security.user.password=pass
jwt.secretKey =thisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkey